# Default values for gateway-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

# Used to label resources
cluster_name: babylon-gateway-cluster

alerts:
  enabled: true

image:
  repository: docker.io/radixdlt/babylon-ng-gateway-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "1.0.0"

imagePullSecrets:

nameOverride: ""
fullnameOverride: ""

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  periodSeconds: 15
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
  periodSeconds: 10

metrics:
  enabled: false
  port: 1235
  serviceMonitor:
    enabled: true
    interval: 15s
  # Url to a default dashboard for the babylon-gateway to be linked in the alerts
  dashboard_url: https://grafana.com

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add:
    - NET_ADMIN
  privileged: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2m
  hosts: []
  tls: []

resources:
  limits:
    memory: 750Mi
  requests:
    cpu: 475m
    memory: 750Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
- key: "networkGatewayInstance"
  operator: "Equal"
  value: "true"
  effect: "PreferNoSchedule"

config:
  ASPNETCORE_URLS: "http://*:8080"
  logging:
    LogLevel:
      Default: "Information"
      Microsoft_Hosting_Lifetime: "Information"

  postgres:
    hostname: "postgres-postgresql"
    hostnameRO: "postgres-postgresql"
    port: 5432
    dbname: "radixdlt_ledger"
    # Use an already existing secret to get the credentials from
    existingSecret: ""
    existingSecretUsernameKey: username
    existingSecretPasswordKey: password

    min_pool_size: "10"
    max_pool_size: "1000"
    connection_lifetime: "600"
    command_timeout: "600"
    read_buffer_size: "32768"
    write_buffer_size: "32768"

  gatewayapi:
    EnableSwagger: true
    MaxPageSize: ""
    PreventReadRequestsIfDbLedgerIsBehind: ""
    PreventConstructionRequestsIfDbLedgerIsBehind: ""

  network:
    name: mainnet
    # Value to label resources according to the network used
    environment: "mainnet"
    disableCoreAPICertificates: true
    disableFallbackCertificates: true
    nodes:
      # Unique name of the node. 
      - name: Core1
        enabled: true
        address: "https://somehost/core"
        trust_weighting: "1"
        # Use an already existing secret to get the credentials from
        existingSecret: babylon-gateway-core1-credentials
        existingSecretKey: base64-encoded-auth