apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-api.fullname" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "gateway-api.selectorLabels" . | nindent 4 }}
