# Default values for data-aggregator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

alert_thresholds:
  HighTimeSinceLastLedgerCommit: 30

cluster_name: rdx-works-main-dev

alerts:
  enabled: true

image:
  repository: docker.io/radixdlt/ng-babylon-data-aggregator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

imagePullSecrets:
nameOverride: ""
fullnameOverride: ""

migrations:
  enableInitContainer: false

metrics:
  # -- Whether to install/enable the metrics endpoints and collect them using ServiceMonitors
  enabled: false
  port: 1234
  serviceMonitor:
    enabled: true
    interval: 5s
  dashboard_url: https://grafana.com
  
readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  periodSeconds: 15
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
  periodSeconds: 10

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add:
    - NET_ADMIN
  privileged: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
- key: "networkGatewayInstance"
  operator: "Equal"
  value: "true"
  effect: "PreferNoSchedule"

affinity:
  podAffinity: {}

global:
  config:
    # -- The interface the dotnet service listens to. Shared with gateway_api. Defaults to using values under global.config
    ASPNETCORE_URLS: "http://*:8080"
    logging:
      LogLevel:
        Default: "Information"
        Microsoft_Hosting_Lifetime: "Information"
    postgres:
      hostname: "postgres-postgresql"
      hostnameRO: "postgres-postgresql"
      port: 5432
      # -- Name of the database to store the babylon-ledger data in.
      dbname: "radixdlt_ledger"
      # -- Name of the secret that stores the credentials to connect to postgres. Must be created before deployment.
      existingSecret: ""
      # -- Key in the secret that stores the username to connect to postgres. Must be created before deployment.
      existingSecretUsernameKey: username
      # -- Key in the secret that stores the password to connect to postgres. Must be created before deployment.
      existingSecretPasswordKey: password

      min_pool_size: "10"
      max_pool_size: "1000"
      connection_lifetime: "600"
      command_timeout: "600"
      read_buffer_size: "32768"
      write_buffer_size: "32768"

    data_aggregator:
      "MempoolConfiguration":
        "MinDelayBetweenMissingFromMempoolAndResubmissionSeconds": 10
        "MinDelayBetweenResubmissionsSeconds": 10
        "StopResubmittingAfterSeconds": 300
        "PruneCommittedAfterSeconds": "31556952" # one calendar year. This is quoted because it's expected to be passed as a String
        "PruneMissingTransactionsAfterTimeSinceLastGatewaySubmissionSeconds": 604800
        "PruneMissingTransactionsAfterTimeSinceFirstSeenSeconds": 604800
        "PruneRequiresMissingFromMempoolForSeconds": 60
    
      "LedgerConfirmation":
        "QuorumRequiresTrustProportion": 0.51
        "OnlyUseSufficientlySyncedUpNodesForQuorumCalculation": true
        "SufficientlySyncedStateVersionThreshold": 1000
        "MaxCommitBatchSize": 1000
        "MaxTransactionPipelineSizePerNode": 3000

    network:
      # -- Name of the network 
      name: mainnet
      # -- Alternative descriptive name of the network to be put into labels
      environment: "mainnet"
      # -- Whether to check the TLS certificates of the network nodes.
      disableCoreAPICertificates: true
      disableFallbackCertificates: true
      nodes:
        - name: Core1
          # -- Whether to enable this node
          enabled: true
          # -- URL of the core node. Must include the path /core to reach the right API endpoints
          address: "https://somehost/core"
          # -- Trust weighting for creating a priority list
          trust_weighting: "1"
          # -- Credentials to conncet to the core ndoe. The secret must be created seperately before deployment.
          existingSecret: babylon-gateway-core1-credentials
          # -- Key of secret with the base64 encoded core node credentials.
          existingSecretKey: base64-encoded-auth

config:
  # -- The interface the dotnet service listens to. Shared with gateway_api. Defaults to using values under global.config
  ASPNETCORE_URLS: 
  logging:
    LogLevel:
      Default:
      Microsoft_Hosting_Lifetime:

  postgres:
    # -- Hostname of the postgres instance
    hostname: 
    # -- Hostname of Read Only postgres instance
    hostnameRO: 
    # -- Port that the postgres instance listens on
    port: 
    # -- Name of the database to store the babylon-ledger data in. Defaults to using values under global.config
    dbname: 
    # -- Name of the secret that stores the credentials to connect to postgres. Must be created before deployment. Defaults to using values under global.config
    existingSecret: 
    # -- Key in the secret that stores the username to connect to postgres. Must be created before deployment. Defaults to using values under global.config
    existingSecretUsernameKey: 
    # -- Key in the secret that stores the password to connect to postgres. Must be created before deployment. Defaults to using values under global.config
    existingSecretPasswordKey: 
    min_pool_size: 
    max_pool_size: 
    connection_lifetime: 
    command_timeout: 
    read_buffer_size: 
    write_buffer_size: 

  data_aggregator:
    "MempoolConfiguration":
      "MinDelayBetweenMissingFromMempoolAndResubmissionSeconds": 
      "MinDelayBetweenResubmissionsSeconds": 
      "StopResubmittingAfterSeconds": 
      "PruneCommittedAfterSeconds": 
      "PruneMissingTransactionsAfterTimeSinceLastGatewaySubmissionSeconds": 
      "PruneMissingTransactionsAfterTimeSinceFirstSeenSeconds": 
      "PruneRequiresMissingFromMempoolForSeconds": 
    
    "LedgerConfirmation":
      "QuorumRequiresTrustProportion": 
      "OnlyUseSufficientlySyncedUpNodesForQuorumCalculation": 
      "SufficientlySyncedStateVersionThreshold": 
      "MaxCommitBatchSize": 
      "MaxTransactionPipelineSizePerNode": 

  network:
    # -- Name of the network 
    name: 
    # -- Alternative descriptive name of the network to be put into labels
    environment:
    # -- Whether to check the TLS certificates of the network nodes.
    disableCoreAPICertificates: 
    disableFallbackCertificates: 
    # -- List of core nodes to connect to. Use trust_weighting to create a priority list.
    nodes:
      # -- Unique name of the node. 
      # -- - name: Core1
      # --   enabled: true
      # --   address: "https://somehost/core"
      # --   trust_weighting: "1"
      # --   # -- Use an already existing secret to get the credentials from
      # --   existingSecret: babylon-gateway-core1-credentials
      # --   existingSecretKey: base64-encoded-auth